### ISSUE TITLE
Information about the CPU temp script?

### ISSUE THREAD

**Issue by CypSteel** [Otto-G/HomeAutomation#1]
Sorry, I am new to github so I didn't see any other way to contact you.  Thanks for your configuration as I am using it to learn HASS and using it as my model adjusting as necessary.  Where does your temps come from in your Freenas section?

**Comment by Otto-G** [comment]
Since the normal system monitor tools were built with Linux in mind, the stock temp monitors weren't working on freenas. 

All I have is a Cron job that writes the temperature for each item to it's own file. There is some filtering needed (I think I'm using sed to filter the freenas hardware output) to pick out the correct temperature but it works. 

If you need the code, let me know and I'll post it once I have access to the server again/update it (I try to update on weekends so I can fix things that break before the work week).

**Comment by Otto-G** [comment]
Here's the code from Crontab for those sensors.  This will work on Freenas, but I'm not sure about Linux.  You may also need to change the drive numbers. 

    */2 * * * * /sbin/sysctl dev.cpu.0 | grep temperature | cut -c 24-27 > /home/.homeassistant/HomeAutomation/cpu0temp.txt
    */2 * * * * /usr/local/sbin/smartctl -a /dev/ada0 | grep Temperature_Celsius | cut -c 88-90 > /home/.homeassistant/HomeAutomation/HD1temp.txt
    */2 * * * * /usr/local/sbin/smartctl -a /dev/ada1 | grep Temperature_Celsius | cut -c 88-90 > /home/.homeassistant/HomeAutomation/HD2temp.txt
